BuildEmpire/CLA0000_Cookbook_Clarus

recipes/default.rb
Trying to add runit back in (as it doesnt seem to work without it on the server!)
CLA0003-3
=> It was in twice!

attributes/default.rb, metadata.rb, recipes/unicorn.rb
Added the ability to override the nginx configuration back in, as we needed it to define the SSL port and certificates.
CLA0003-3
=> Added the ability to override the nginx configuration back in

attributes/default.rb, metadata.rb, recipes/default.rb, recipes/unicorn.rb
Added the ability to override the nginx configuration back in, as we needed it to define the SSL port and certificates.
CLA0003-3
=> M2M - Added the ability to override the nginx configuration back in

metadata.rb, recipes/ftpd.rb
Changed the way the pg gem in installed (command so I can set ARCHFLAGS) as the re-provision didn't seem to work without it.
CLA0003-3
=> Changed the way the pg gem in installed

libraries/helpers.rb, metadata.rb, recipes/ftpd.rb, recipes/ruby.rb, templates/default/nginx_vhost.conf.erb
I think the issue was that the global rbenv wasnt there, so I've tried to resolve that.
Fixed an issue with the path in the nginx configuration.
CLA0003-3
=> Reverted the installation of PG back as it made no difference.

libraries/helpers.rb, metadata.rb, recipes/ftpd.rb, recipes/ruby.rb, templates/default/nginx_vhost.conf.erb
I think the issue was that the global rbenv wasnt there, so I've tried to resolve that.
Fixed an issue with the path in the nginx configuration.
CLA0003-3
=> M2M - Reverted the installation of PG back as it made no difference.

metadata.rb, recipes/ruby.rb, recipes/wkhtmltopdf.rb
These are for wkhtmltopdf.
Additionally removed the ruby global command as it still doesnt work, but im sure we need it!
#CLA0003-7 Fixed
=> CLA0003-7 - Setting some more default values

metadata.rb
Added wkhtmltopdf to the dependencies, but cant see this being the issue.
CLA0003-7
=> CLA0003-7 - wkhtmltopdf amends

metadata.rb, recipes/ruby.rb
Attempting to make the ruby we install the global one. Again.
CLA0003-11 Fixed
=> CLA0003-11 - Add Global Ruby

attributes/default.rb, metadata.rb
As the cookbook is currently failing as the URL doesn't exist to the old version.
#CLA0003-12 Fixed
=> CLA0003-12 - Update PureFTPD To 1.0.43

attributes/default.rb, metadata.rb, recipes/ftpd.rb, recipes/wkhtmltopdf.rb
We're now using the new cookbook for this, and also improved the pureftpd installation process so we can set a different version and url if required.
#CLA0003-13 Fixed
=> CLA0003-13 - Update wkhtmltopdf

attributes/default.rb, metadata.rb, recipes/ftpd.rb, recipes/wkhtmltopdf.rb
CLA0003-13 Update wkhtmltopdf
We're now using the new cookbook for this, and also improved the pureftpd installation process so we can set a different version and url if required.
#CLA0003-13 Fixed
=> M2M - CLA0003-13 - Update wkhtmltopdf

templates/default/ftp-auth-handler.erb
This seems like it hasn't worked for a while.
=> Fixed the FTP service settings so that they have the correct table lookup

metadata.rb, recipes/wkhtmltopdf.rb
=> Updated the mirror url for the cookbook, as the old url doesn't work.

templates/default/ftp-auth-handler.erb
As a user who is connecting to the FTP to upload a file I wish for the server to automatically create the uploads path for the user on the mounted S3 bucket for the subdomain
=> #CLA0003-755 fixed

metadata.rb, recipes/postgresql.rb
As a developer I wish to set the pg_gem version to an older version as the latest version of postgresql has broken this
See here
https://github.com/sous-chefs/postgresql/issues/480
CLA0003-897
=> CLA0003-897 - Postgres PG gem version

metadata.rb, recipes/default.rb, recipes/postgresql.rb
Attempting another fix for this.
=> CLA0003-897 - Postgres PG Gem Lock

metadata.rb, recipes/default.rb, recipes/postgresql.rb
=> CLA0003-897 - Postgres PG Gem Lock 

attributes/default.rb, metadata.rb
Forgot to update part of the version.
=> CLA0003-953 - PureFTP Version to 1.0.47 Fix!

attributes/default.rb, metadata.rb
Forgot to update part of the version.
=> M2M - CLA0003-953 - PureFTP Version to 1.0.47 Fix!

metadata.rb, templates/default/ftp-auth-handler.erb
CLA0003-1018 As an FTP user I wish to be connected to the new storage location so that I can download or upload my files.
CLA0003-1020 As an FTP user I wish to be able to use my FTP username as my username to achieve successful login as that its easy for me to use
=> Use ftp user for ftp auth

metadata.rb, recipes/nginx.rb, recipes/papertrail.rb, recipes/wkhtmltopdf.rb
`node.set` is now deprecated.
https://docs.chef.io/deprecations_attributes.html
=> Update deprecated Chef method.

metadata.rb, recipes/ftpd.rb
CLA0003-1019 As an FTP user I wish to be restricted to only downloading the files in the folder if the user I am logging in as is of Download type so that I can share the FTP account safely.
=> Enable ftp throttling
